// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Product struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	ImageUrl    sql.NullString
}

type RefreshToken struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         string
	Name       string
	Email      string
	Password   sql.NullString
	Provider   string
	ProviderID sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
