// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Order struct {
	ID          string
	UserID      sql.NullString
	TotalAmount string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrdersItem struct {
	ID         string
	OrderID    string
	ProductID  string
	Quantity   int32
	Price      string
	TotalPrice string
}

type Payment struct {
	ID            string
	OrderID       string
	PaymentMethod string
	Amount        string
	PaymentStatus string
	PaymentDate   time.Time
}

type Product struct {
	ID          string
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	ImageUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID         string
	Name       string
	Email      string
	Password   sql.NullString
	Provider   string
	ProviderID sql.NullString
	Phone      sql.NullString
	Address    sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
