// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Order struct {
	ID                string
	UserID            string
	TotalAmount       string
	Status            string
	PaymentMethod     sql.NullString
	ExternalPaymentID sql.NullString
	TrackingNumber    sql.NullString
	ShippingAddress   sql.NullString
	ContactPhone      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type OrderItem struct {
	ID        string
	OrderID   string
	ProductID string
	Quantity  int32
	Price     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	ID                string
	OrderID           string
	UserID            string
	Amount            string
	Currency          string
	Status            string
	Provider          string
	ProviderPaymentID sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Product struct {
	ID          string
	CategoryID  sql.NullString
	Name        string
	Description sql.NullString
	Price       string
	Stock       int32
	ImageUrl    sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID         string
	Name       string
	Email      string
	Password   sql.NullString
	Provider   string
	ProviderID sql.NullString
	Phone      sql.NullString
	Address    sql.NullString
	Role       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
