// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const checkExistsAndGetIDByEmail = `-- name: CheckExistsAndGetIDByEmail :one
SELECT 
    (id IS NOT NULL)::boolean AS exists, 
    COALESCE(id, '') AS id
FROM users
WHERE email = $1
LIMIT 1
`

type CheckExistsAndGetIDByEmailRow struct {
	Exists bool
	ID     string
}

func (q *Queries) CheckExistsAndGetIDByEmail(ctx context.Context, email string) (CheckExistsAndGetIDByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, checkExistsAndGetIDByEmail, email)
	var i CheckExistsAndGetIDByEmailRow
	err := row.Scan(&i.Exists, &i.ID)
	return i, err
}

const checkUserExistsByEmail = `-- name: CheckUserExistsByEmail :one
SELECT EXISTS (SELECT email FROM users WHERE email = $1)
`

func (q *Queries) CheckUserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserExistsByName = `-- name: CheckUserExistsByName :one
SELECT EXISTS (SELECT name FROM users WHERE name = $1)
`

func (q *Queries) CheckUserExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, email, password, provider, provider_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserParams struct {
	ID         string
	Name       string
	Email      string
	Password   sql.NullString
	Provider   string
	ProviderID sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Provider,
		arg.ProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, provider, provider_id, phone, address, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.ProviderID,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSigninStatusByEmail = `-- name: UpdateUserSigninStatusByEmail :exec
UPDATE users
SET updated_at = $1, provider = $2, Provider_id = $3
WHERE email = $4
`

type UpdateUserSigninStatusByEmailParams struct {
	UpdatedAt  time.Time
	Provider   string
	ProviderID sql.NullString
	Email      string
}

func (q *Queries) UpdateUserSigninStatusByEmail(ctx context.Context, arg UpdateUserSigninStatusByEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSigninStatusByEmail,
		arg.UpdatedAt,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
	)
	return err
}

const updateUserStatusByID = `-- name: UpdateUserStatusByID :exec
UPDATE users
SET updated_at = $1, provider = $2
WHERE id = $3
`

type UpdateUserStatusByIDParams struct {
	UpdatedAt time.Time
	Provider  string
	ID        string
}

func (q *Queries) UpdateUserStatusByID(ctx context.Context, arg UpdateUserStatusByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByID, arg.UpdatedAt, arg.Provider, arg.ID)
	return err
}
