-- -- name: CreateProduct :exec
-- INSERT INTO products (id, category_id, name, description, price, stock, image_url, is_active, created_at, updated_at)
-- VALUES (
--     $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
-- );