name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Set environment variables
        env:
          ISSUER: ${{ secrets.ISSUER }}
          AUDIENCE: ${{ secrets.AUDIENCE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
        run: echo "Load environment variables"

      - name: Run unit tests
        run: go test ./... -cover

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Check for formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
